In [78]:
import pandas as pd

In [79]:
df_lastfm = pd.read_csv('../../data/processed/lastfm_transformed.csv')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,Troye Sivan,She’s the Best,2026-10-19 14:01:03-03:00,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,14:01:03,Monday,0,14
1,Troye Sivan,She’s the Best,2026-10-19 13:57:27-03:00,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:57:27,Monday,0,13
2,Troye Sivan,She’s the Best,2026-10-19 13:53:54-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:53:54,Monday,0,13
3,Tinashe,POPSTAR,2026-10-18 17:37:00-03:00,POPSTAR,396a9525-0994-4542-b480-c4587feeb476,2026-10-18,17:37:00,Sunday,6,17
4,Mollie Elizabeth,Run Rabbit,2026-10-18 16:27:43-03:00,Run Rabbit,adef6e0a-0610-45df-8a17-55aa92a47c15,2026-10-18,16:27:43,Sunday,6,16
5,Tinashe,POPSTAR,2026-10-18 16:24:28-03:00,I’d Rather Be Alone,396a9525-0994-4542-b480-c4587feeb476,2026-10-18,16:24:28,Sunday,6,16
6,Troye Sivan,She’s the Best,2026-10-18 16:21:06-03:00,Canada Dry,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,16:21:06,Sunday,6,16
7,Troye Sivan,She’s the Best,2026-10-18 16:17:42-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,16:17:42,Sunday,6,16
8,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-18 16:13:54-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-18,16:13:54,Sunday,6,16
9,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-18 16:10:25-03:00,stupid song,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-18,16:10:25,Sunday,6,16

In [80]:
df_mb= pd.read_csv('../../data/processed/musicBrainz_transformed.csv')

In [81]:
print(df_lastfm.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour']

In [82]:
print(df_mb.columns.tolist())

['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'query_name', 'legal_name', 'music_genre']

In [83]:
# Padroniza os nomes: remove espaços nas pontas e converte para minúsculas
df_lastfm['nome_chave'] = df_lastfm['artist_name'].str.strip().str.lower()
df_mb['nome_chave'] = df_mb['query_name'].str.strip().str.lower()
# padroniza nomes de artistas ex: willow, que no musicBrainz aparecia como WILLOW

# Mantém todas as linhas da tabela Last.fm
df_final = df_lastfm.merge(
    df_mb,
    on='nome_chave',
    how='left',
    validate="many_to_one"
)

# Remove a coluna auxiliar do resultado
df_final = df_final.drop(columns=['nome_chave'])
# query_name é a "ponte" garantida entre as duas tabelas, porque ela nasceu do mesmo valor original.
df_final = df_final.drop(columns='id')

In [84]:
# df_final = df_lastfm.merge(df_mb, left_on='artist_name', right_on='name', how='left')
# #last_fm -> tabela base
# #left_on= tabela da esquerda e chave de comparação
# #right_on= tabela da direita + chave de comparação
# #how=left -> mantem todas as linhas da tabela principal mesmo que não haja relação com a outra tabela

In [85]:
df_final.head(50)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,Troye Sivan,She’s the Best,2026-10-19 14:01:03-03:00,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,14:01:03,Monday,0,14,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
1,Troye Sivan,She’s the Best,2026-10-19 13:57:27-03:00,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:57:27,Monday,0,13,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
2,Troye Sivan,She’s the Best,2026-10-19 13:53:54-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:53:54,Monday,0,13,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
3,Tinashe,POPSTAR,2026-10-18 17:37:00-03:00,POPSTAR,396a9525-0994-4542-b480-c4587feeb476,2026-10-18,17:37:00,Sunday,6,17,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop
4,Mollie Elizabeth,Run Rabbit,2026-10-18 16:27:43-03:00,Run Rabbit,adef6e0a-0610-45df-8a17-55aa92a47c15,2026-10-18,16:27:43,Sunday,6,16,Person,Mollie Elizabeth,female,unregistered,Subdivision,Washington,Mollie Elizabeth,unregistered,pop
5,Tinashe,POPSTAR,2026-10-18 16:24:28-03:00,I’d Rather Be Alone,396a9525-0994-4542-b480-c4587feeb476,2026-10-18,16:24:28,Sunday,6,16,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop
6,Troye Sivan,She’s the Best,2026-10-18 16:21:06-03:00,Canada Dry,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,16:21:06,Sunday,6,16,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
7,Troye Sivan,She’s the Best,2026-10-18 16:17:42-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,16:17:42,Sunday,6,16,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
8,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-18 16:13:54-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-18,16:13:54,Sunday,6,16,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
9,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-18 16:10:25-03:00,stupid song,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-18,16:10:25,Sunday,6,16,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
10,Troye Sivan,She’s the Best,2026-10-18 16:06:12-03:00,Canada Dry,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,16:06:12,Sunday,6,16,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
11,Troye Sivan,She’s the Best,2026-10-18 00:38:19-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-18,00:38:19,Sunday,6,0,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
12,Troye Sivan,She’s the Best,2026-10-16 19:29:09-03:00,Canada Dry,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-16,19:29:09,Friday,4,19,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
13,Marina Sena,Coisas Naturais,2026-10-16 13:51:40-03:00,Desmitificar,2b1e7c27-2663-43df-9c23-8601e173e6ef,2026-10-16,13:51:40,Friday,4,13,Person,Marina Sena,female,BR,Country,Brazil,Marina Sena,Marina de Oliveira Sena,pop
14,Roberta Campos,Varrendo A Lua,2026-10-16 12:49:45-03:00,De Janeiro a Janeiro,3cfbe5fb-c638-40dc-b8d8-bb5e5c9c4a1e,2026-10-16,12:49:45,Friday,4,12,NaN,NaN,unregistered,unregistered,unregistered,unregistered,Roberta Campos,unregistered,unregistered
15,Marina Sena,Coisas Naturais,2026-10-16 11:09:01-03:00,Lua Cheia,2b1e7c27-2663-43df-9c23-8601e173e6ef,2026-10-16,11:09:01,Friday,4,11,Person,Marina Sena,female,BR,Country,Brazil,Marina Sena,Marina de Oliveira Sena,pop
16,Banda Nova reação,Nada Vai Adiantar,2026-10-16 11:02:54-03:00,Nada Vai Adiantar,NaN,2026-10-16,11:02:54,Friday,4,11,Group,Nova Banda,unregistered,unregistered,unregistered,unregistered,Banda Nova reação,unregistered,unregistered
17,Jão,SUPERNOVA,2026-10-16 11:01:13-03:00,Carnaval,6797c795-08b4-4da2-a4d8-95a554c2a91c,2026-10-16,11:01:13,Friday,4,11,Person,Jão,male,BR,Country,Brazil,Jão,João Vitor Romania Balbino,pop
18,Chico Buarque,Sinal Fechado,2026-10-16 10:58:51-03:00,Acorda Amor,3a5d1cc7-627e-48ea-aba3-fdd20d782c33,2026-10-16,10:58:51,Friday,4,10,Person,Chico Buarque,male,BR,Country,Brazil,Chico Buarque,Francisco Buarque de Hollanda,mpb
19,Anitta,Ensaios da Anitta,2026-10-16 10:58:46-03:00,Só Pra Tu,d606b860-cc03-4959-a3fd-3a24bccf2560,2026-10-16,10:58:46,Friday,4,10,Person,Anitta,female,BR,Country,Brazil,Anitta,Larissa de Macedo Machado,funk
20,Olivia Rodrigo,expectations (feat. Chappell Roan),2026-10-16 00:09:47-03:00,expectations,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-16,00:09:47,Friday,4,0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
21,Olivia Rodrigo,expectations (feat. Chappell Roan),2026-10-15 21:52:58-03:00,expectations (feat. Chappell Roan),6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-15,21:52:58,Thursday,3,21,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
22,Marina Sena,Coisas Naturais,2026-10-15 20:52:52-03:00,Desmitificar,2b1e7c27-2663-43df-9c23-8601e173e6ef,2026-10-15,20:52:52,Thursday,3,20,Person,Marina Sena,female,BR,Country,Brazil,Marina Sena,Marina de Oliveira Sena,pop
23,Fafá de Belém,Pássaro Sonhador,2026-10-15 20:49:04-03:00,Vermelho,7df5de77-f197-4326-805e-2b2a128feb25,2026-10-15,20:49:04,Thursday,3,20,Person,Fafá de Belém,female,BR,Country,Brazil,Fafá de Belém,Maria de Fátima Palha de Figueiredo,carimbó
24,Tate McRae,SO CLOSE TO WHAT??? (deluxe),2026-10-15 14:24:26-03:00,TRYING ON SHOES,f9133869-f87c-459c-9aa7-2f176cda7e06,2026-10-15,14:24:26,Thursday,3,14,Person,Tate McRae,female,CA,Country,Canada,Tate McRae,Tate Rosner McRae,pop
25,Gilberto Gil,Um Banda Um,2026-10-15 11:29:33-03:00,Deixar Você - primeira versão,cf6b70f6-2616-481c-912c-0263cabfc974,2026-10-15,11:29:33,Thursday,3,11,Person,Gilberto Gil,male,BR,Country,Brazil,Gilberto Gil,Gilberto Passos Gil Moreira,mpb
26,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-15,11:25:26,Thursday,3,11,Group,BaianaSystem,unregistered,BR,Country,Brazil,BaianaSystem,unregistered,rock
27,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,NaN,2026-10-15,11:21:39,Thursday,3,11,NaN,O Surto,unregistered,unregistered,unregistered,unregistered,O Surto,unregistered,unregistered
28,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1,2026-10-15,11:16:06,Thursday,3,11,Group,Natiruts,unregistered,BR,Country,Brazil,Natiruts,unregistered,reggae
29,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-15,11:12:03,Thursday,3,11,Group,Mariasss,unregistered,BR,Country,Brazil,Mariasss,unregistered,unregistered
30,Lady Zu,DIVERSOS,2026-10-15 11:08:15-03:00,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65,2026-10-15,11:08:15,Thursday,3,11,Person,Lady Zu,female,BR,Country,Brazil,Lady Zu,unregistered,brazilian
31,Oriente,Desorientado,2026-10-15 11:03:09-03:00,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256,2026-10-15,11:03:09,Thursday,3,11,Group,Oriente,unregistered,BR,Country,Brazil,Oriente,unregistered,unregistered
32,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,NaN,2026-10-15,11:00:10,Thursday,3,11,Group,Los Hermanos,unregistered,BR,Country,Brazil,Los Hermanos,unregistered,rock
33,Seu Jorge,"Musica Para Churrasco, Vol. 1",2026-10-15 10:56:01-03:00,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241,2026-10-15,10:56:01,Thursday,3,10,Person,Seu Jorge,male,BR,Country,Brazil,Seu Jorge,Jorge Mário da Silva,brazilian
34,Arlindo Cruz,Sambista Perfeito,2026-10-15 10:51:07-03:00,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f,2026-10-15,10:51:07,Thursday,3,10,Person,Arlindo Cruz,male,BR,Country,Brazil,Arlindo Cruz,Arlindo Domingos da Cruz Filho,samba
35,Marisa Monte,Portas,2026-10-15 10:48:55-03:00,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb,2026-10-15,10:48:55,Thursday,3,10,Person,Marisa Monte,female,BR,Country,Brazil,Marisa Monte,Marisa de Azevedo Monte,singer-songwriter
36,Tate McRae,SO CLOSE TO WHAT??? (deluxe),2026-10-15 07:25:04-03:00,TRYING ON SHOES,f9133869-f87c-459c-9aa7-2f176cda7e06,2026-10-15,07:25:04,Thursday,3,7,Person,Tate McRae,female,CA,Country,Canada,Tate McRae,Tate Rosner McRae,pop
37,Phia,French Riviera,2026-10-15 07:21:29-03:00,French Riviera,b9fd792f-6ffd-4d56-aa1c-5696196989f9,2026-10-15,07:21:29,Thursday,3,7,Person,Phia,female,unregistered,City,Berlin,Phia,unregistered,unregistered
38,Tate McRae,SO CLOSE TO WHAT??? (deluxe),2026-10-15 07:18:27-03:00,HORSESHOE,f9133869-f87c-459c-9aa7-2f176cda7e06,2026-10-15,07:18:27,Thursday,3,7,Person,Tate McRae,female,CA,Country,Canada,Tate McRae,Tate Rosner McRae,pop
39,One Direction,Made in the A.M. (Deluxe Edition),2026-10-15 07:14:37-03:00,Perfect,1a425bbd-cca4-4b2c-aeb7-71cb176c828a,2026-10-15,07:14:37,Thursday,3,7,Group,One Direction,unregistered,unregistered,Subdivision,England,One Direction,unregistered,pop
40,Tyla,She Did It Again (feat. Zara Larsson),2026-10-15 07:10:55-03:00,SHE DID IT AGAIN (feat. Zara Larsson),45425c84-9092-4e2c-b732-e1d0280b580a,2026-10-15,07:10:55,Thursday,3,7,Person,Tyla,male,GB,Country,United Kingdom,Tyla,unregistered,spike
41,Wham!,Make It Big,2026-10-15 07:05:51-03:00,Everything She Wants,d570bb31-b9ca-45a4-a2d9-11b186d9c159,2026-10-15,07:05:51,Thursday,3,7,Group,Wham!,unregistered,GB,Country,United Kingdom,Wham!,unregistered,pop
42,Madison Beer,Locket DELUXE,2026-10-15 07:03:14-03:00,complexity,749ef494-8518-4b49-b685-63d8e728d25c,2026-10-15,07:03:14,Thursday,3,7,Person,Madison Beer,female,US,Country,United States,Madison Beer,Madison Elle Beer,pop
43,Madison Beer,Locket DELUXE,2026-10-15 07:00:00-03:00,lovergirl,749ef494-8518-4b49-b685-63d8e728d25c,2026-10-15,07:00:00,Thursday,3,7,Person,Madison Beer,female,US,Country,United States,Madison Beer,Madison Elle Beer,pop
44,ADÉLA,Red Bottoms,2026-10-15 06:55:41-03:00,Red Bottoms,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-15,06:55:41,Thursday,3,6,Person,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,pop
45,Clairo,Immunity,2026-10-15 06:55:07-03:00,North,d786f59b-1836-4ddb-8393-ab753edbe984,2026-10-15,06:55:07,Thursday,3,6,Person,Clairo,female,US,Country,United States,Clairo,Claire Elizabeth Cottrill,bedroom pop
46,Katy Perry,PRISM,2026-10-15 06:47:48-03:00,Legendary Lovers,122d63fc-8671-43e4-9752-34e846d62a9c,2026-10-15,06:47:48,Thursday,3,6,Person,Katy Perry,female,US,Country,United States,Katy Perry,Katheryn Elizabeth Hudson,pop
47,Kali Uchis,"Sincerely,",2026-10-15 06:44:48-03:00,It's Just Us,d0c7656d-8169-4f77-9dbe-b8f24e40105d,2026-10-15,06:44:48,Thursday,3,6,Person,Kali Uchis,female,US,Country,United States,Kali Uchis,Karly-Marina Loaiza,neo soul
48,Troye Sivan,Spotify Singles,2026-10-15 06:41:06-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-15,06:41:06,Thursday,3,6,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
49,Troye Sivan,In a Dream,2026-10-15 06:37:08-03:00,Easy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-15,06:37:08,Thursday,3,6,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop

In [86]:
# colunas_mb = [
#     'id', 'type', 'name', 'gender', 'country',
#     'area.type', 'area.name', 'legal_name', 'music_genre'
# ]

# df_final[colunas_mb] = df_final[colunas_mb].fillna('unregistered')

In [87]:
df_final.isna().sum()

artist_name        0
album_name         0
scrobble_date      0
music_name         0
artist_mbid      104
date               0
time               0
week_day           0
week_day_id        0
group_hour         0
type              30
name               1
gender             0
country            0
area.type          0
area.name          0
query_name         0
legal_name         0
music_genre        0
dtype: int64

In [88]:
df_final[df_final['artist_mbid'].isna()]

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
16,Banda Nova reação,Nada Vai Adiantar,2026-10-16 11:02:54-03:00,Nada Vai Adiantar,NaN,2026-10-16,11:02:54,Friday,4,11,Group,Nova Banda,unregistered,unregistered,unregistered,unregistered,Banda Nova reação,unregistered,unregistered
27,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,NaN,2026-10-15,11:21:39,Thursday,3,11,NaN,O Surto,unregistered,unregistered,unregistered,unregistered,O Surto,unregistered,unregistered
32,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,NaN,2026-10-15,11:00:10,Thursday,3,11,Group,Los Hermanos,unregistered,BR,Country,Brazil,Los Hermanos,unregistered,rock
90,a-ha,Lifelines,2026-10-12 14:17:59-03:00,Lifelines - 2019 Remaster,NaN,2026-10-12,14:17:59,Monday,0,14,Group,a‐ha,unregistered,NO,Country,Norway,a-ha,unregistered,new wave
139,Jennie,FALLEN ANGEL,2026-10-12 11:01:17-03:00,Fallen Angel,NaN,2026-10-12,11:01:17,Monday,0,11,Person,JENNIE,female,KR,Country,South Korea,Jennie,김제니,k-pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,Jennie,FALLEN ANGEL,2026-09-14 13:32:16-03:00,Fallen Angel,NaN,2026-09-14,13:32:16,Monday,0,13,Person,JENNIE,female,KR,Country,South Korea,Jennie,김제니,k-pop
1346,Kersty,ELECTRONS,2026-09-14 13:25:45-03:00,ELECTRONS,NaN,2026-09-14,13:25:45,Monday,0,13,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1351,Kersty,ELECTRONS,2026-09-12 10:41:22-03:00,ELECTRONS,NaN,2026-09-12,10:41:22,Saturday,5,10,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1376,Miley Cyrus,Can't Be Tamed,2026-09-10 14:08:55-03:00,Who Owns My Heart,NaN,2026-09-10,14:08:55,Thursday,3,14,Person,Miley Cyrus,non-binary,US,Country,United States,Miley Cyrus,Miley Ray Cyrus,pop
1404,Adele,21,2026-09-06 19:20:21-03:00,Lovesong,NaN,2026-09-06,19:20:21,Sunday,6,19,Person,Adele,female,GB,Country,United Kingdom,Adele,Adele Adkins,pop

In [89]:
# sem_match = df_final[df_final['id'].isna()]['artist_name'].unique()
# print(sem_match)

In [90]:
df_final['artist_mbid'] = df_final['artist_mbid'].fillna('unregistered')

In [91]:
df_final.isna().sum()

artist_name       0
album_name        0
scrobble_date     0
music_name        0
artist_mbid       0
date              0
time              0
week_day          0
week_day_id       0
group_hour        0
type             30
name              1
gender            0
country           0
area.type         0
area.name         0
query_name        0
legal_name        0
music_genre       0
dtype: int64

In [92]:
df_final[df_final['query_name'].isna()]['artist_name'].unique() #checando artistas que tiveram falhas na hora da extração de dados e tiveram problemas 
# de correspondência entre tabelas. A query_name é a ponte garantida entre as duas tabelas

<StringArray>
[]
Length: 0, dtype: str

In [93]:
df_final[df_final['type'].isna()][['query_name', 'name']].drop_duplicates()

           query_name             name
14     Roberta Campos              NaN
27            O Surto          O Surto
241   Pequeno Cidadão  Pequeno Cidadão
257            Kersty      Kersty Ryan
347       Flora Matos      Flora Matos
565  Bloco Da Saudade            Bloco
748      Rio Carnaval     Rio Carnaval

In [94]:
colunas = ['artist_mbid','type', 'name', 'gender', 'country', 'area.type', 'area.name', 'legal_name', 'music_genre']
df_final[colunas] = df_final[colunas].fillna('unregistered')

In [95]:
df_final.head(4)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,Troye Sivan,She’s the Best,2026-10-19 14:01:03-03:00,Le Boy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,14:01:03,Monday,0,14,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
1,Troye Sivan,She’s the Best,2026-10-19 13:57:27-03:00,emBARRAssingly,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:57:27,Monday,0,13,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
2,Troye Sivan,She’s the Best,2026-10-19 13:53:54-03:00,Cowboy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-19,13:53:54,Monday,0,13,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
3,Tinashe,POPSTAR,2026-10-18 17:37:00-03:00,POPSTAR,396a9525-0994-4542-b480-c4587feeb476,2026-10-18,17:37:00,Sunday,6,17,Person,Tinashe,female,US,Country,United States,Tinashe,Tinashe Jorgenson Kachingwe,pop

In [96]:
df_final.isna().sum()

artist_name      0
album_name       0
scrobble_date    0
music_name       0
artist_mbid      0
date             0
time             0
week_day         0
week_day_id      0
group_hour       0
type             0
name             0
gender           0
country          0
area.type        0
area.name        0
query_name       0
legal_name       0
music_genre      0
dtype: int64

In [97]:
# VERIFICAR SE O TAMANHO DAS TABELAS SEGUE IGUAL, POIS O MERGE PODE TER GERADO LINHAS A MAIS OU A MENOS
assert len(df_final) == len(df_lastfm), print(
    f"Quantidade de linhas mudou: "
    f"{len(df_lastfm)} antes e {len(df_final)} depois."
)

print(f"Quantidade de escutas preservada: {len(df_final):,}")

Quantidade de escutas preservada: 1,411

In [98]:
# CHAVE DOS METADADOS É ÚNICA,ENTÃO NÃO PODE HAVER REPETIÇÃO
chave = "query_name"  # use a chave efetivamente utilizada no merge

duplicados = df_mb[
    df_mb.duplicated(subset=[chave], keep=False)
].sort_values(chave)

display(duplicados)

assert duplicados.empty, "Existem chaves repetidas nos metadados."

Empty DataFrame
Columns: [id, type, name, gender, country, area.type, area.name, query_name, legal_name, music_genre, nome_chave]
Index: []

In [99]:
print(df_final.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'query_name', 'legal_name', 'music_genre']

In [100]:
colunas_evento = ["artist_name", "music_name", "time"]  # ajuste os nomes

possiveis_duplicatas = df_final[
    df_final.duplicated(subset=colunas_evento, keep=False)
].sort_values(colunas_evento)

print(f"Linhas envolvidas: {len(possiveis_duplicatas)}")
display(possiveis_duplicatas)

Linhas envolvidas: 0

Empty DataFrame
Columns: [artist_name, album_name, scrobble_date, music_name, artist_mbid, date, time, week_day, week_day_id, group_hour, type, name, gender, country, area.type, area.name, query_name, legal_name, music_genre]
Index: []

In [101]:
df_lastfm.to_csv('../../data/processed/data_final.csv', index=False)