In [94]:
import pandas as pd

In [95]:
df_lastfm = pd.read_csv('../../data/processed/lastfm_transformed.csv')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,Gilberto Gil,Um Banda Um,2026-10-01 14:17:56-03:00,Deixar Você - primeira versão,cf6b70f6-2616-481c-912c-0263cabfc974,2026-10-01,14:17:56,Thursday,3,14
1,Pabllo Vittar,Amor de Que,2026-10-01 14:15:17-03:00,Amor de Que,d9550ac2-7bcf-4655-a3fe-24922e254a74,2026-10-01,14:15:17,Thursday,3,14
2,Djavan,Lilás,2026-10-01 14:11:23-03:00,Miragem,751e517d-9663-4692-8c20-942e16d484c5,2026-10-01,14:11:23,Thursday,3,14
3,Katinguelê,No Compasso Do Criador,2026-10-01 14:07:20-03:00,Recado a minha amada,3b72c1fa-34cd-4b28-b9dc-bf4e15a303df,2026-10-01,14:07:20,Thursday,3,14
4,Mariasss,Flert3,2026-10-01 14:05:01-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-01,14:05:01,Thursday,3,14
5,Jão,Memórias Póstumas,2026-10-01 13:43:48-03:00,O Arquiteto,6797c795-08b4-4da2-a4d8-95a554c2a91c,2026-10-01,13:43:48,Thursday,3,13
6,BaianaSystem,O Futuro Não Demora,2026-10-01 13:39:48-03:00,Sulamericano,15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-01,13:39:48,Thursday,3,13
7,George Michael,Ladies & Gentlemen,2026-10-01 07:29:41-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-01,07:29:41,Thursday,3,7
8,Lizzy McAlpine,Angel,2026-10-01 07:24:34-03:00,Over Country,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-10-01,07:24:34,Thursday,3,7
9,Say Now,Met my match,2026-10-01 07:21:49-03:00,Met my match,6df684dc-704e-4bd3-8abb-e2f89260fe8e,2026-10-01,07:21:49,Thursday,3,7

In [96]:
df_mb= pd.read_csv('../../data/processed/musicBrainz_transformed.csv')

In [97]:
print(df_lastfm.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour']

In [98]:
print(df_mb.columns.tolist())

['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'legal_name', 'music_genre']

In [99]:
# Padroniza os nomes: remove espaços nas pontas e converte para minúsculas
df_lastfm['nome_chave'] = df_lastfm['artist_name'].str.strip().str.lower()
df_mb['nome_chave'] = df_mb['name'].str.strip().str.lower()
# padroniza nomes de artistas ex: willow, que no musicBrainz aparecia como WILLOW

# Mantém todas as linhas da tabela Last.fm
df_final = df_lastfm.merge(
    df_mb,
    on='nome_chave',
    how='left'
)

# Remove a coluna auxiliar do resultado
df_final = df_final.drop(columns=['nome_chave'])

In [100]:
# df_final = df_lastfm.merge(df_mb, left_on='artist_name', right_on='name', how='left')
# #last_fm -> tabela base
# #left_on= tabela da esquerda e chave de comparação
# #right_on= tabela da direita + chave de comparação
# #how=left -> mantem todas as linhas da tabela principal mesmo que não haja relação com a outra tabela

In [104]:
df_final.head(50)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,legal_name,music_genre
0,Gilberto Gil,Um Banda Um,2026-10-01 14:17:56-03:00,Deixar Você - primeira versão,cf6b70f6-2616-481c-912c-0263cabfc974,2026-10-01,14:17:56,Thursday,3,14,cf6b70f6-2616-481c-912c-0263cabfc974,Legal name,Gilberto Gil,male,BR,Country,Brazil,Gilberto Passos Gil Moreira,singer-songwriter
1,Pabllo Vittar,Amor de Que,2026-10-01 14:15:17-03:00,Amor de Que,d9550ac2-7bcf-4655-a3fe-24922e254a74,2026-10-01,14:15:17,Thursday,3,14,d9550ac2-7bcf-4655-a3fe-24922e254a74,Legal name,Pabllo Vittar,non-binary,BR,Country,Brazil,Phabullo Rodrigues da Silva,drag queen
2,Djavan,Lilás,2026-10-01 14:11:23-03:00,Miragem,751e517d-9663-4692-8c20-942e16d484c5,2026-10-01,14:11:23,Thursday,3,14,751e517d-9663-4692-8c20-942e16d484c5,Legal name,Djavan,male,BR,Country,Brazil,Djavan Caetano Viana,singer-songwriter
3,Katinguelê,No Compasso Do Criador,2026-10-01 14:07:20-03:00,Recado a minha amada,3b72c1fa-34cd-4b28-b9dc-bf4e15a303df,2026-10-01,14:07:20,Thursday,3,14,3b72c1fa-34cd-4b28-b9dc-bf4e15a303df,unregisterd,Katinguelê,unregisterd,BR,Country,Brazil,unregistered,samba
4,Mariasss,Flert3,2026-10-01 14:05:01-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-01,14:05:01,Thursday,3,14,593d64f5-f8df-4f90-8bd6-ef06986f1e31,unregisterd,Mariasss,unregisterd,BR,Country,Brazil,unregistered,unregisterd
5,Jão,Memórias Póstumas,2026-10-01 13:43:48-03:00,O Arquiteto,6797c795-08b4-4da2-a4d8-95a554c2a91c,2026-10-01,13:43:48,Thursday,3,13,6797c795-08b4-4da2-a4d8-95a554c2a91c,Legal name,Jão,male,BR,Country,Brazil,João Vitor Romania Balbino,pop
6,BaianaSystem,O Futuro Não Demora,2026-10-01 13:39:48-03:00,Sulamericano,15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-01,13:39:48,Thursday,3,13,15741996-1794-42a8-a2c7-1ce3e32d0d75,unregisterd,BaianaSystem,unregisterd,BR,Country,Brazil,unregistered,rock
7,George Michael,Ladies & Gentlemen,2026-10-01 07:29:41-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-01,07:29:41,Thursday,3,7,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregisterd,George Michael,male,GB,Country,United Kingdom,Georgios Kyriacos Panayiotou,rock
8,Lizzy McAlpine,Angel,2026-10-01 07:24:34-03:00,Over Country,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-10-01,07:24:34,Thursday,3,7,ee0b11de-0c8a-4267-9886-198f4579e1db,Legal name,Lizzy McAlpine,female,unregisterd,City,Philadelphia,Elizabeth Catherine McAlpine,singer-songwriter
9,Say Now,Met my match,2026-10-01 07:21:49-03:00,Met my match,6df684dc-704e-4bd3-8abb-e2f89260fe8e,2026-10-01,07:21:49,Thursday,3,7,6df684dc-704e-4bd3-8abb-e2f89260fe8e,unregisterd,Say Now,unregisterd,GB,Country,United Kingdom,unregistered,pop
10,Michael Sembello,Maniac (Flashdance Version) (Re-Recorded / Rem...,2026-10-01 07:17:29-03:00,Maniac (Flashdance Version) (Re-Recorded / Rem...,fcde7037-181e-437f-9417-60a38958c0fa,2026-10-01,07:17:29,Thursday,3,7,fcde7037-181e-437f-9417-60a38958c0fa,unregisterd,Michael Sembello,male,US,Country,United States,Michael Andrew Sembello,pop
11,Troye Sivan,Bloom,2026-10-01 07:12:58-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-01,07:12:58,Thursday,3,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan Mellet,synthpop
12,ADÉLA,Ain't In LA,2026-10-01 07:09:49-03:00,Ain't In LA,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-01,07:09:49,Thursday,3,7,f40856e6-079f-4a0a-916e-9e6a5e04f646,Artist name,ADÉLA,female,SK,Country,Slovakia,Adéla Jergová,electronic
13,Willow,t r a n s p a r e n t s o u l feat. Travis Barker,2026-10-01 07:07:00-03:00,t r a n s p a r e n t s o u l feat. Travis Barker,NaN,2026-10-01,07:07:00,Thursday,3,7,6bbfc71b-5f18-4e61-82fb-bee0c2a6b5f9,Artist name,WILLOW,female,US,Country,United States,Willow Camille Reign Smith,punk rock
14,Kali Uchis,"Sincerely,",2026-10-01 07:04:03-03:00,It's Just Us,d0c7656d-8169-4f77-9dbe-b8f24e40105d,2026-10-01,07:04:03,Thursday,3,7,d0c7656d-8169-4f77-9dbe-b8f24e40105d,Artist name,Kali Uchis,female,US,Country,United States,Karly-Marina Loaiza,neo soul
15,The 1975,"I like it when you sleep, for you are so beaut...",2026-10-01 06:58:11-03:00,Somebody Else,5b6ebfe0-f72b-4902-bba9-74c8af0f1af0,2026-10-01,06:58:11,Thursday,3,6,5b6ebfe0-f72b-4902-bba9-74c8af0f1af0,Artist name,The 1975,unregisterd,GB,Country,United Kingdom,unregistered,rock
16,beabadoobee,Beatopia,2026-10-01 06:55:14-03:00,broken cd,88d17133-abbc-42db-9526-4e2c1db60336,2026-10-01,06:55:14,Thursday,3,6,88d17133-abbc-42db-9526-4e2c1db60336,unregisterd,beabadoobee,female,unregisterd,Subdivision,England,Beatrice Laus,rock
17,Clairo,Sling,2026-10-01 06:50:37-03:00,Amoeba,d786f59b-1836-4ddb-8393-ab753edbe984,2026-10-01,06:50:37,Thursday,3,6,d786f59b-1836-4ddb-8393-ab753edbe984,Artist name,Clairo,female,US,Country,United States,Claire Elizabeth Cottrill,pop
18,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-01 06:46:45-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-01,06:46:45,Thursday,3,6,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Isabel Rodrigo,rock
19,Troye Sivan,Spotify Singles,2026-10-01 06:43:03-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-01,06:43:03,Thursday,3,6,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan Mellet,synthpop
20,XG,AWE,2026-10-01 06:40:28-03:00,IS THIS LOVE,8dfe067c-ae90-472e-80f2-fcee9be4e158,2026-10-01,06:40:28,Thursday,3,6,8dfe067c-ae90-472e-80f2-fcee9be4e158,Artist name,XG,unregisterd,KR,Country,South Korea,unregistered,pop
21,Sabrina Carpenter,Man’s Best Friend,2026-10-01 06:37:23-03:00,Sugar Talking,1882fe91-cdd9-49c9-9956-8e06a3810bd4,2026-10-01,06:37:23,Thursday,3,6,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Artist name,Sabrina Carpenter,female,US,Country,United States,Sabrina Annlynn Carpenter,pop
22,Lizzy McAlpine,Angel,2026-10-01 06:31:27-03:00,Over Country,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-10-01,06:31:27,Thursday,3,6,ee0b11de-0c8a-4267-9886-198f4579e1db,Legal name,Lizzy McAlpine,female,unregisterd,City,Philadelphia,Elizabeth Catherine McAlpine,singer-songwriter
23,George Michael,Ladies & Gentlemen,2026-10-01 06:23:51-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-01,06:23:51,Thursday,3,6,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregisterd,George Michael,male,GB,Country,United Kingdom,Georgios Kyriacos Panayiotou,rock
24,Michael Sembello,Maniac (Flashdance Version) (Re-Recorded / Rem...,2026-10-01 06:23:46-03:00,Maniac (Flashdance Version) (Re-Recorded / Rem...,fcde7037-181e-437f-9417-60a38958c0fa,2026-10-01,06:23:46,Thursday,3,6,fcde7037-181e-437f-9417-60a38958c0fa,unregisterd,Michael Sembello,male,US,Country,United States,Michael Andrew Sembello,pop
25,Natanzinho Lima,Cortando Chão (Ao Vivo),2026-09-30 22:37:51-03:00,Sonho de Amor - Ao Vivo,NaN,2026-09-30,22:37:51,Wednesday,2,22,643d2df5-7b25-433d-9965-2df4a33b95a7,unregisterd,Natanzinho Lima,unregisterd,BR,Country,Brazil,unregistered,unregisterd
26,George Michael,Ladies & Gentlemen,2026-09-30 22:16:39-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-09-30,22:16:39,Wednesday,2,22,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregisterd,George Michael,male,GB,Country,United Kingdom,Georgios Kyriacos Panayiotou,rock
27,BTS,WINGS,2026-09-30 22:04:21-03:00,Blood Sweat & Tears,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,22:04:21,Wednesday,2,22,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
28,RM,Indigo,2026-09-30 22:00:11-03:00,Hectic (with Colde),3be217fb-2b91-4911-9454-6de69751f53b,2026-09-30,22:00:11,Wednesday,2,22,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Legal name,RM,male,KR,Country,South Korea,Nam-joon Kim,pop
29,Jung Kook,GOLDEN,2026-09-30 21:57:22-03:00,Somebody,23c8056b-ee13-4cfc-a772-2f5292e35bb5,2026-09-30,21:57:22,Wednesday,2,21,23c8056b-ee13-4cfc-a772-2f5292e35bb5,Legal name,Jung Kook,male,KR,Country,South Korea,Jeon Jung-kook,pop
30,BTS,The Most Beautiful Moment in Life: Young Forever,2026-09-30 21:52:14-03:00,Butterfly (Prologue Mix),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:52:14,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
31,BTS,Proof,2026-09-30 21:48:46-03:00,Moon,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:48:46,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
32,BTS,Proof,2026-09-30 21:44:58-03:00,Jamais Vu,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:44:58,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
33,BTS,LOVE YOURSELF 結 'Answer',2026-09-30 21:40:59-03:00,FAKE LOVE (Rocking Vibe Mix),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:40:59,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
34,BTS,LOVE YOURSELF 承 'Her',2026-09-30 21:36:40-03:00,Pied Piper,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:36:40,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
35,f5ve,SEQUENCE 01.5 (dreaming of the 2nd 1st impact ...,2026-09-30 21:31:13-03:00,I Choose You,9bdce94a-7c47-4b9a-8e10-f65f5fc63d32,2026-09-30,21:31:13,Wednesday,2,21,9bdce94a-7c47-4b9a-8e10-f65f5fc63d32,Artist name,f5ve,unregisterd,JP,Country,Japan,unregistered,j-pop
36,Olivia Rodrigo,SOUR,2026-09-30 21:26:48-03:00,enough for you,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-09-30,21:26:48,Wednesday,2,21,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Artist name,Olivia Rodrigo,female,US,Country,United States,Olivia Isabel Rodrigo,rock
37,BTS,Come Over,2026-09-30 21:23:49-03:00,Come Over,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-09-30,21:23:49,Wednesday,2,21,0d79fe8e-ba27-4859-bb8c-2f255f346853,Search hint,BTS,unregisterd,KR,Country,South Korea,unregistered,pop
38,Kersty,CATASTROPHIC CHEMICALS,2026-09-30 21:20:23-03:00,CATASTROPHIC CHEMICALS,NaN,2026-09-30,21:20:23,Wednesday,2,21,unregistered,unregistered,unregistered,unregistered,unregistered,unregistered,unregistered,unregistered,unregistered
39,t.A.T.u.,200 KM/H In The Wrong Lane (10th Anniversary E...,2026-09-30 21:16:48-03:00,All the Things She Said,7c20f558-d664-42bd-b6f1-81acf9dbb72d,2026-09-30,21:16:48,Wednesday,2,21,7c20f558-d664-42bd-b6f1-81acf9dbb72d,Artist name,t.A.T.u.,unregisterd,RU,Country,Russia,unregistered,rock
40,George Michael,Ladies & Gentlemen,2026-09-30 19:17:59-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-09-30,19:17:59,Wednesday,2,19,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,unregisterd,George Michael,male,GB,Country,United Kingdom,Georgios Kyriacos Panayiotou,rock
41,Lizzy McAlpine,Angel,2026-09-30 19:12:53-03:00,Over Country,ee0b11de-0c8a-4267-9886-198f4579e1db,2026-09-30,19:12:53,Wednesday,2,19,ee0b11de-0c8a-4267-9886-198f4579e1db,Legal name,Lizzy McAlpine,female,unregisterd,City,Philadelphia,Elizabeth Catherine McAlpine,singer-songwriter
42,Michael Sembello,Maniac (Flashdance Version) (Re-Recorded / Rem...,2026-09-30 19:08:33-03:00,Maniac (Flashdance Version) (Re-Recorded / Rem...,fcde7037-181e-437f-9417-60a38958c0fa,2026-09-30,19:08:33,Wednesday,2,19,fcde7037-181e-437f-9417-60a38958c0fa,unregisterd,Michael Sembello,male,US,Country,United States,Michael Andrew Sembello,pop
43,Troye Sivan,Bloom,2026-09-30 19:03:43-03:00,The Good Side,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-09-30,19:03:43,Wednesday,2,19,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan Mellet,synthpop
44,Troye Sivan,could cry just thinkin about you (Full Version),2026-09-30 19:01:04-03:00,could cry just thinkin about you - Full Version,NaN,2026-09-30,19:01:04,Wednesday,2,19,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan Mellet,synthpop
45,Troye Sivan,Blue Neighbourhood,2026-09-30 18:57:41-03:00,COOL,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-09-30,18:57:41,Wednesday,2,18,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Artist name,Troye Sivan,male,AU,Country,Australia,Troye Sivan Mellet,synthpop
46,Japanese Breakfast,Jubilee,2026-09-30 18:54:26-03:00,Be Sweet,8c529495-91f5-4e2f-b71b-adcb66878d04,2026-09-30,18:54:26,Wednesday,2,18,8c529495-91f5-4e2f-b71b-adcb66878d04,Legal name,Japanese Breakfast,unregisterd,US,Country,United States,Michelle Zauner,indie rock
47,Say Now,Met my match,2026-09-30 18:51:40-03:00,Met my match,6df684dc-704e-4bd3-8abb-e2f89260fe8e,2026-09-30,18:51:40,Wednesday,2,18,6df684dc-704e-4bd3-8abb-e2f89260fe8e,unregisterd,Say Now,unregisterd,GB,Country,United Kingdom,unregistered,pop
48,KARLEE GIRL,Right Back!,2026-09-30 18:48:21-03:00,Right Back!,ae1a5bb8-a7d8-4a77-9099-e18b45ca506b,2026-09-30,18:48:21,Wednesday,2,18,ae1a5bb8-a7d8-4a77-9099-e18b45ca506b,Artist name,KARLEE GIRL,female,US,Country,United States,Karlee Tanaka,unregisterd
49,Phoebe Bridgers,"Lost Ark Studio Compilation, Vol. 8",2026-09-30 18:41:46-03:00,Waiting Room,96855c21-b832-4366-ba12-0d2330c36a86,2026-09-30,18:41:46,Wednesday,2,18,96855c21-b832-4366-ba12-0d2330c36a86,unregisterd,Phoebe Bridgers,female,US,Country,United States,unregistered,folk

In [102]:
colunas_mb = [
    'id', 'type', 'name', 'gender', 'country',
    'area.type', 'area.name', 'legal_name', 'music_genre'
]

df_final[colunas_mb] = df_final[colunas_mb].fillna('unregistered')

In [103]:
df_final.isna().sum()

artist_name       0
album_name        0
scrobble_date     0
music_name        0
artist_mbid      98
date              0
time              0
week_day          0
week_day_id       0
group_hour        0
id                0
type              0
name              0
gender            0
country           0
area.type         0
area.name         0
legal_name        0
music_genre       0
dtype: int64