In [1]:
import pandas as pd

In [2]:
df_lastfm = pd.read_csv('../../data/processed/lastfm_transformed.csv')
df_lastfm.head(10)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour
0,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-15,11:25:26,Thursday,3,11
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,NaN,2026-10-15,11:21:39,Thursday,3,11
2,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1,2026-10-15,11:16:06,Thursday,3,11
3,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-15,11:12:03,Thursday,3,11
4,Lady Zu,DIVERSOS,2026-10-15 11:08:15-03:00,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65,2026-10-15,11:08:15,Thursday,3,11
5,Oriente,Desorientado,2026-10-15 11:03:09-03:00,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256,2026-10-15,11:03:09,Thursday,3,11
6,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,NaN,2026-10-15,11:00:10,Thursday,3,11
7,Seu Jorge,"Musica Para Churrasco, Vol. 1",2026-10-15 10:56:01-03:00,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241,2026-10-15,10:56:01,Thursday,3,10
8,Arlindo Cruz,Sambista Perfeito,2026-10-15 10:51:07-03:00,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f,2026-10-15,10:51:07,Thursday,3,10
9,Marisa Monte,Portas,2026-10-15 10:48:55-03:00,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb,2026-10-15,10:48:55,Thursday,3,10

In [3]:
df_mb= pd.read_csv('../../data/processed/musicBrainz_transformed.csv')

In [4]:
print(df_lastfm.columns.tolist())

['artist_name', 'album_name', 'scrobble_date', 'music_name', 'artist_mbid', 'date', 'time', 'week_day', 'week_day_id', 'group_hour']

In [5]:
print(df_mb.columns.tolist())

['id', 'type', 'name', 'gender', 'country', 'area.type', 'area.name', 'query_name', 'legal_name', 'music_genre']

In [6]:
# Padroniza os nomes: remove espaços nas pontas e converte para minúsculas
df_lastfm['nome_chave'] = df_lastfm['artist_name'].str.strip().str.lower()
df_mb['nome_chave'] = df_mb['query_name'].str.strip().str.lower()
# padroniza nomes de artistas ex: willow, que no musicBrainz aparecia como WILLOW

# Mantém todas as linhas da tabela Last.fm
df_final = df_lastfm.merge(
    df_mb,
    on='nome_chave',
    how='left'
)

# Remove a coluna auxiliar do resultado
df_final = df_final.drop(columns=['nome_chave'])
# query_name é a "ponte" garantida entre as duas tabelas, porque ela nasceu do mesmo valor original.

In [7]:
# df_final = df_lastfm.merge(df_mb, left_on='artist_name', right_on='name', how='left')
# #last_fm -> tabela base
# #left_on= tabela da esquerda e chave de comparação
# #right_on= tabela da direita + chave de comparação
# #how=left -> mantem todas as linhas da tabela principal mesmo que não haja relação com a outra tabela

In [8]:
df_final.head(50)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-15,11:25:26,Thursday,3,11,15741996-1794-42a8-a2c7-1ce3e32d0d75,Group,BaianaSystem,unregistered,BR,Country,Brazil,BaianaSystem,unregistered,rock
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,NaN,2026-10-15,11:21:39,Thursday,3,11,143cd620-88f9-4c58-a2c1-46028166d020,NaN,O Surto,unregistered,unregistered,unregistered,unregistered,O Surto,unregistered,unregistered
2,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1,2026-10-15,11:16:06,Thursday,3,11,917e448b-fbed-4062-b563-67566a3b3bb1,Group,Natiruts,unregistered,BR,Country,Brazil,Natiruts,unregistered,reggae
3,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-15,11:12:03,Thursday,3,11,593d64f5-f8df-4f90-8bd6-ef06986f1e31,Group,Mariasss,unregistered,BR,Country,Brazil,Mariasss,unregistered,unregistered
4,Lady Zu,DIVERSOS,2026-10-15 11:08:15-03:00,Junto a Mim,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65,2026-10-15,11:08:15,Thursday,3,11,c3b70ec4-e13d-47dd-a9a6-94229ed4bc65,Person,Lady Zu,female,BR,Country,Brazil,Lady Zu,unregistered,brazilian
5,Oriente,Desorientado,2026-10-15 11:03:09-03:00,O vagabundo e a dama,69d485d1-de5d-4284-b089-74b91336b256,2026-10-15,11:03:09,Thursday,3,11,69d485d1-de5d-4284-b089-74b91336b256,Group,Oriente,unregistered,BR,Country,Brazil,Oriente,unregistered,unregistered
6,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,NaN,2026-10-15,11:00:10,Thursday,3,11,557ac15e-7800-44c3-bb62-d4ab34ac1e28,Group,Los Hermanos,unregistered,BR,Country,Brazil,Los Hermanos,unregistered,rock
7,Seu Jorge,"Musica Para Churrasco, Vol. 1",2026-10-15 10:56:01-03:00,Amiga da Minha Mulher,c73d651d-87c9-4c5e-8abb-4ec9c4077241,2026-10-15,10:56:01,Thursday,3,10,c73d651d-87c9-4c5e-8abb-4ec9c4077241,Person,Seu Jorge,male,BR,Country,Brazil,Seu Jorge,Jorge Mário da Silva,brazilian
8,Arlindo Cruz,Sambista Perfeito,2026-10-15 10:51:07-03:00,Meu Lugar,a0e7903d-cde4-4433-8487-8b7b130d715f,2026-10-15,10:51:07,Thursday,3,10,a0e7903d-cde4-4433-8487-8b7b130d715f,Person,Arlindo Cruz,male,BR,Country,Brazil,Arlindo Cruz,Arlindo Domingos da Cruz Filho,samba
9,Marisa Monte,Portas,2026-10-15 10:48:55-03:00,Totalmente Seu,f81f19b9-c76e-43ac-8656-bb56071785fb,2026-10-15,10:48:55,Thursday,3,10,f81f19b9-c76e-43ac-8656-bb56071785fb,Person,Marisa Monte,female,BR,Country,Brazil,Marisa Monte,Marisa de Azevedo Monte,singer-songwriter
10,Tate McRae,SO CLOSE TO WHAT??? (deluxe),2026-10-15 07:25:04-03:00,TRYING ON SHOES,f9133869-f87c-459c-9aa7-2f176cda7e06,2026-10-15,07:25:04,Thursday,3,7,f9133869-f87c-459c-9aa7-2f176cda7e06,Person,Tate McRae,female,CA,Country,Canada,Tate McRae,Tate Rosner McRae,pop
11,Phia,French Riviera,2026-10-15 07:21:29-03:00,French Riviera,b9fd792f-6ffd-4d56-aa1c-5696196989f9,2026-10-15,07:21:29,Thursday,3,7,b9fd792f-6ffd-4d56-aa1c-5696196989f9,Person,Phia,female,unregistered,City,Berlin,Phia,unregistered,unregistered
12,Tate McRae,SO CLOSE TO WHAT??? (deluxe),2026-10-15 07:18:27-03:00,HORSESHOE,f9133869-f87c-459c-9aa7-2f176cda7e06,2026-10-15,07:18:27,Thursday,3,7,f9133869-f87c-459c-9aa7-2f176cda7e06,Person,Tate McRae,female,CA,Country,Canada,Tate McRae,Tate Rosner McRae,pop
13,One Direction,Made in the A.M. (Deluxe Edition),2026-10-15 07:14:37-03:00,Perfect,1a425bbd-cca4-4b2c-aeb7-71cb176c828a,2026-10-15,07:14:37,Thursday,3,7,1a425bbd-cca4-4b2c-aeb7-71cb176c828a,Group,One Direction,unregistered,unregistered,Subdivision,England,One Direction,unregistered,pop
14,Tyla,She Did It Again (feat. Zara Larsson),2026-10-15 07:10:55-03:00,SHE DID IT AGAIN (feat. Zara Larsson),45425c84-9092-4e2c-b732-e1d0280b580a,2026-10-15,07:10:55,Thursday,3,7,2bf761c6-4bcf-4cfc-a388-8fcb2eea8cc8,Person,Tyla,male,GB,Country,United Kingdom,Tyla,unregistered,spike
15,Wham!,Make It Big,2026-10-15 07:05:51-03:00,Everything She Wants,d570bb31-b9ca-45a4-a2d9-11b186d9c159,2026-10-15,07:05:51,Thursday,3,7,d570bb31-b9ca-45a4-a2d9-11b186d9c159,Group,Wham!,unregistered,GB,Country,United Kingdom,Wham!,unregistered,pop
16,Madison Beer,Locket DELUXE,2026-10-15 07:03:14-03:00,complexity,749ef494-8518-4b49-b685-63d8e728d25c,2026-10-15,07:03:14,Thursday,3,7,749ef494-8518-4b49-b685-63d8e728d25c,Person,Madison Beer,female,US,Country,United States,Madison Beer,Madison Elle Beer,pop
17,Madison Beer,Locket DELUXE,2026-10-15 07:00:00-03:00,lovergirl,749ef494-8518-4b49-b685-63d8e728d25c,2026-10-15,07:00:00,Thursday,3,7,749ef494-8518-4b49-b685-63d8e728d25c,Person,Madison Beer,female,US,Country,United States,Madison Beer,Madison Elle Beer,pop
18,ADÉLA,Red Bottoms,2026-10-15 06:55:41-03:00,Red Bottoms,f40856e6-079f-4a0a-916e-9e6a5e04f646,2026-10-15,06:55:41,Thursday,3,6,f40856e6-079f-4a0a-916e-9e6a5e04f646,Person,ADÉLA,female,SK,Country,Slovakia,ADÉLA,Adéla Jergová,pop
19,Clairo,Immunity,2026-10-15 06:55:07-03:00,North,d786f59b-1836-4ddb-8393-ab753edbe984,2026-10-15,06:55:07,Thursday,3,6,d786f59b-1836-4ddb-8393-ab753edbe984,Person,Clairo,female,US,Country,United States,Clairo,Claire Elizabeth Cottrill,bedroom pop
20,Katy Perry,PRISM,2026-10-15 06:47:48-03:00,Legendary Lovers,122d63fc-8671-43e4-9752-34e846d62a9c,2026-10-15,06:47:48,Thursday,3,6,122d63fc-8671-43e4-9752-34e846d62a9c,Person,Katy Perry,female,US,Country,United States,Katy Perry,Katheryn Elizabeth Hudson,pop
21,Kali Uchis,"Sincerely,",2026-10-15 06:44:48-03:00,It's Just Us,d0c7656d-8169-4f77-9dbe-b8f24e40105d,2026-10-15,06:44:48,Thursday,3,6,d0c7656d-8169-4f77-9dbe-b8f24e40105d,Person,Kali Uchis,female,US,Country,United States,Kali Uchis,Karly-Marina Loaiza,neo soul
22,Troye Sivan,Spotify Singles,2026-10-15 06:41:06-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-15,06:41:06,Thursday,3,6,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
23,Troye Sivan,In a Dream,2026-10-15 06:37:08-03:00,Easy,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-15,06:37:08,Thursday,3,6,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
24,Troye Sivan,Blue Neighbourhood,2026-10-15 06:33:23-03:00,COOL,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-15,06:33:23,Thursday,3,6,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
25,George Michael,Ladies & Gentlemen,2026-10-15 06:17:36-03:00,Cowboys And Angels - 2010 Remastered Version,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,2026-10-15,06:17:36,Thursday,3,6,ccb8f30e-4d71-40c4-8b1d-846dafe73e2c,Person,George Michael,male,GB,Country,United Kingdom,George Michael,Georgios Kyriacos Panayiotou,pop
26,RM,"Right Place, Wrong Person",2026-10-14 19:24:35-03:00,ㅠㅠ (Credit Roll),3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,19:24:35,Wednesday,2,19,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
27,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:17:12-03:00,Converse High,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:17:12,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
28,RM,Indigo,2026-10-14 13:13:57-03:00,No.2 (with parkjiyoon),3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,13:13:57,Wednesday,2,13,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
29,BTS,The Most Beautiful Moment in Life: Young Forever,2026-10-14 13:10:11-03:00,House Of Cards (Full Length Edition),0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:10:11,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
30,BTS,ARIRANG,2026-10-14 13:06:53-03:00,Please,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,13:06:53,Wednesday,2,13,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
31,BTS,Skool Luv Affair,2026-10-14 12:48:52-03:00,JUMP,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:48:52,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
32,BTS,FAKE LOVE (Rocking Vibe Mix),2026-10-14 12:44:23-03:00,FAKE LOVE - Rocking Vibe Mix,NaN,2026-10-14,12:44:23,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
33,RM,mono.,2026-10-14 12:42:07-03:00,moonchild,3be217fb-2b91-4911-9454-6de69751f53b,2026-10-14,12:42:07,Wednesday,2,12,58f1e354-ecbc-4fd3-aa25-97eb1d9bd8b9,Person,RM,male,KR,Country,South Korea,RM,Nam-joon Kim,pop
34,BTS,ARIRANG,2026-10-14 12:38:57-03:00,Body to Body,0d79fe8e-ba27-4859-bb8c-2f255f346853,2026-10-14,12:38:57,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
35,Taylor Swift,Red (Taylor's Version),2026-10-14 07:45:18-03:00,Sad Beautiful Tragic (Taylor's Version),20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:45:18,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
36,Taylor Swift,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,2026-10-14 07:42:44-03:00,I Look in People's Windows,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:42:44,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
37,Olivia Rodrigo,Serena Joy,2026-10-14 07:39:19-03:00,serena joy,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:39:19,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
38,Taylor Swift,folklore,2026-10-14 07:36:04-03:00,this is me trying,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:36:04,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
39,Olivia Rodrigo,All I Want (Love That Lasts Mix),2026-10-14 07:33:02-03:00,All I Want - Love That Lasts Mix,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:33:02,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
40,Olivia Rodrigo,The Hunger Games: The Ballad of Songbirds & Sn...,2026-10-14 07:29:36-03:00,Can’t Catch Me Now - from The Hunger Games: Th...,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:29:36,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
41,Clairo,Charm,2026-10-14 07:25:56-03:00,Add Up My Love,d786f59b-1836-4ddb-8393-ab753edbe984,2026-10-14,07:25:56,Wednesday,2,7,d786f59b-1836-4ddb-8393-ab753edbe984,Person,Clairo,female,US,Country,United States,Clairo,Claire Elizabeth Cottrill,bedroom pop
42,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 07:22:42-03:00,less,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:22:42,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
43,Troye Sivan,Spotify Singles,2026-10-14 07:19:00-03:00,Bloom - Recorded At Spotify Studios NYC,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,2026-10-14,07:19:00,Wednesday,2,7,e5712ceb-c37a-4c49-a11c-ccf4e21852d4,Person,Troye Sivan,male,AU,Country,Australia,Troye Sivan,Troye Sivan Mellet,pop
44,Taylor Swift,Red (Taylor's Version),2026-10-14 07:08:46-03:00,All Too Well (10 Minute Version) (Taylor's Ver...,20244d07-534f-4eff-b4d4-930878889970,2026-10-14,07:08:46,Wednesday,2,7,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
45,Olivia Rodrigo,SOUR,2026-10-14 07:05:16-03:00,hope ur ok,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:05:16,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
46,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 07:01:16-03:00,purple,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,07:01:16,Wednesday,2,7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop
47,Taylor Swift,1989 (Taylor's Version),2026-10-14 06:58:15-03:00,"""Slut!"" (Taylor's Version) (From the Vault)",20244d07-534f-4eff-b4d4-930878889970,2026-10-14,06:58:15,Wednesday,2,6,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
48,Taylor Swift,THE TORTURED POETS DEPARTMENT,2026-10-14 06:53:51-03:00,"So Long, London",20244d07-534f-4eff-b4d4-930878889970,2026-10-14,06:53:51,Wednesday,2,6,20244d07-534f-4eff-b4d4-930878889970,Person,Taylor Swift,female,US,Country,United States,Taylor Swift,Taylor Alison Swift,pop
49,Olivia Rodrigo,you seem pretty sad for a girl so in love,2026-10-14 06:50:08-03:00,honeybee,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,2026-10-14,06:50:08,Wednesday,2,6,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,Olivia Rodrigo,female,US,Country,United States,Olivia Rodrigo,Olivia Isabel Rodrigo,pop

In [9]:
# colunas_mb = [
#     'id', 'type', 'name', 'gender', 'country',
#     'area.type', 'area.name', 'legal_name', 'music_genre'
# ]

# df_final[colunas_mb] = df_final[colunas_mb].fillna('unregistered')

In [10]:
df_final.isna().sum()

artist_name        0
album_name         0
scrobble_date      0
music_name         0
artist_mbid      138
date               0
time               0
week_day           0
week_day_id        0
group_hour         0
id                 0
type              29
name               0
gender             0
country            0
area.type          0
area.name          0
query_name         0
legal_name         0
music_genre        0
dtype: int64

In [11]:
df_final[df_final['artist_mbid'].isna()]

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,NaN,2026-10-15,11:21:39,Thursday,3,11,143cd620-88f9-4c58-a2c1-46028166d020,NaN,O Surto,unregistered,unregistered,unregistered,unregistered,O Surto,unregistered,unregistered
6,Los Hermanos,Bloco do Eu Sozinho,2026-10-15 11:00:10-03:00,Adeus Você,NaN,2026-10-15,11:00:10,Thursday,3,11,557ac15e-7800-44c3-bb62-d4ab34ac1e28,Group,Los Hermanos,unregistered,BR,Country,Brazil,Los Hermanos,unregistered,rock
32,BTS,FAKE LOVE (Rocking Vibe Mix),2026-10-14 12:44:23-03:00,FAKE LOVE - Rocking Vibe Mix,NaN,2026-10-14,12:44:23,Wednesday,2,12,0d79fe8e-ba27-4859-bb8c-2f255f346853,Group,BTS,unregistered,KR,Country,South Korea,BTS,unregistered,k-pop
63,a-ha,Lifelines,2026-10-12 14:17:59-03:00,Lifelines - 2019 Remaster,NaN,2026-10-12,14:17:59,Monday,0,14,7364dea6-ca9a-48e3-be01-b44ad0d19897,Group,a‐ha,unregistered,NO,Country,Norway,a-ha,unregistered,new wave
104,Frank Sinatra,Nothing But The Best (2008 Remastered),2026-10-12 11:29:39-03:00,My Way - 2008 Remastered,NaN,2026-10-12,11:29:39,Monday,0,11,197450cd-0124-4164-b723-3c22dd16494d,Person,Frank Sinatra,male,US,Country,United States,Frank Sinatra,Francis Albert Sinatra,jazz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,Jennie,FALLEN ANGEL,2026-09-14 13:32:16-03:00,Fallen Angel,NaN,2026-09-14,13:32:16,Monday,0,13,779351de-0da5-4943-928b-495a3c40e8c0,Person,JENNIE,female,KR,Country,South Korea,Jennie,김제니,k-pop
1319,Kersty,ELECTRONS,2026-09-14 13:25:45-03:00,ELECTRONS,NaN,2026-09-14,13:25:45,Monday,0,13,5925e68f-721d-444e-afe4-32dd019c45c2,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1324,Kersty,ELECTRONS,2026-09-12 10:41:22-03:00,ELECTRONS,NaN,2026-09-12,10:41:22,Saturday,5,10,5925e68f-721d-444e-afe4-32dd019c45c2,NaN,Kersty Ryan,unregistered,unregistered,unregistered,unregistered,Kersty,unregistered,unregistered
1349,Miley Cyrus,Can't Be Tamed,2026-09-10 14:08:55-03:00,Who Owns My Heart,NaN,2026-09-10,14:08:55,Thursday,3,14,7e9bd05a-117f-4cce-87bc-e011527a8b18,Person,Miley Cyrus,non-binary,US,Country,United States,Miley Cyrus,Miley Ray Cyrus,pop
1377,Adele,21,2026-09-06 19:20:21-03:00,Lovesong,NaN,2026-09-06,19:20:21,Sunday,6,19,cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493,Person,Adele,female,GB,Country,United Kingdom,Adele,Adele Adkins,pop

In [12]:
# sem_match = df_final[df_final['id'].isna()]['artist_name'].unique()
# print(sem_match)

In [13]:
df_final['artist_mbid'] = df_final['artist_mbid'].fillna('unregistered')

In [14]:
df_final.isna().sum()

artist_name       0
album_name        0
scrobble_date     0
music_name        0
artist_mbid       0
date              0
time              0
week_day          0
week_day_id       0
group_hour        0
id                0
type             29
name              0
gender            0
country           0
area.type         0
area.name         0
query_name        0
legal_name        0
music_genre       0
dtype: int64

In [15]:
df_final[df_final['query_name'].isna()]['artist_name'].unique() #checando artistas que tiveram falhas na hora da extração de dados e tiveram problemas 
# de correspondência entre tabelas. A query_name é a ponte garantida entre as duas tabelas

<StringArray>
[]
Length: 0, dtype: str

In [16]:
df_final[df_final['type'].isna()][['query_name', 'name']].drop_duplicates()

           query_name             name
1             O Surto          O Surto
214   Pequeno Cidadão  Pequeno Cidadão
230            Kersty      Kersty Ryan
320       Flora Matos      Flora Matos
538  Bloco Da Saudade            Bloco
721      Rio Carnaval     Rio Carnaval

In [17]:
colunas = ['artist_mbid','type', 'name', 'gender', 'country', 'area.type', 'area.name', 'legal_name', 'music_genre']
df_final[colunas] = df_final[colunas].fillna('unregistered')

In [18]:
df_final.head(4)

,artist_name,album_name,scrobble_date,music_name,artist_mbid,date,time,week_day,week_day_id,group_hour,id,type,name,gender,country,area.type,area.name,query_name,legal_name,music_genre
0,BaianaSystem,Duas Cidades,2026-10-15 11:25:26-03:00,Lucro (Descomprimindo),15741996-1794-42a8-a2c7-1ce3e32d0d75,2026-10-15,11:25:26,Thursday,3,11,15741996-1794-42a8-a2c7-1ce3e32d0d75,Group,BaianaSystem,unregistered,BR,Country,Brazil,BaianaSystem,unregistered,rock
1,O Surto,Todo Mundo Doido,2026-10-15 11:21:39-03:00,A Cera,unregistered,2026-10-15,11:21:39,Thursday,3,11,143cd620-88f9-4c58-a2c1-46028166d020,unregistered,O Surto,unregistered,unregistered,unregistered,unregistered,O Surto,unregistered,unregistered
2,Natiruts,Box Natiruts,2026-10-15 11:16:06-03:00,"Sorri, Sou Rei (feat. Claudia Leitte)",917e448b-fbed-4062-b563-67566a3b3bb1,2026-10-15,11:16:06,Thursday,3,11,917e448b-fbed-4062-b563-67566a3b3bb1,Group,Natiruts,unregistered,BR,Country,Brazil,Natiruts,unregistered,reggae
3,Mariasss,Flert3,2026-10-15 11:12:03-03:00,Flert3,593d64f5-f8df-4f90-8bd6-ef06986f1e31,2026-10-15,11:12:03,Thursday,3,11,593d64f5-f8df-4f90-8bd6-ef06986f1e31,Group,Mariasss,unregistered,BR,Country,Brazil,Mariasss,unregistered,unregistered

In [19]:
df_final.isna().sum()

artist_name      0
album_name       0
scrobble_date    0
music_name       0
artist_mbid      0
date             0
time             0
week_day         0
week_day_id      0
group_hour       0
id               0
type             0
name             0
gender           0
country          0
area.type        0
area.name        0
query_name       0
legal_name       0
music_genre      0
dtype: int64