In [8]:
import json
import pandas as pd

In [9]:
dados_artistas = {}

with open("../../data/raw/musicbrainz_data.json", "r", encoding="utf-8") as arquivo:
    dados_artistas = json.load(arquivo)

df_mb = pd.DataFrame.from_dict(dados_artistas, orient="index") 
#ajustando para tratar as chaves externas como as linhas da tabela, não as colunas (padrão)
# index se refere as chaves externas como linhas

df_mb.head(10)

# count mostra quantos outros artistas semelhantes batem com a nossa busca

,created,count,offset,artists
CMAT,2026-09-21T20:54:11.975Z,14,0,[{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens,2026-09-21T20:54:13.790Z,1044,0,[{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter,2026-09-21T20:54:18.346Z,658,0,[{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores,2026-09-21T20:54:20.514Z,1772,0,[{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença,2026-09-21T20:54:22.708Z,15,0,[{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...
Tinashe,2026-09-21T20:54:24.812Z,14,0,[{'id': '396a9525-0994-4542-b480-c4587feeb476'...
Zé Ibarra,2026-09-21T20:54:26.898Z,530,0,[{'id': '0b2665a9-14c0-499a-b9fd-46ed09bbf161'...
Olivia Rodrigo,2026-09-21T20:54:28.990Z,1303,0,[{'id': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0'...
Pabllo Vittar,2026-09-21T20:53:57.262Z,3,0,[{'id': 'd9550ac2-7bcf-4655-a3fe-24922e254a74'...
Lana Del Rey,2026-09-21T20:54:33.200Z,29385,0,[{'id': 'b7539c32-53e7-4908-bda3-81449c367da6'...

In [10]:
df_mb.shape

(103, 4)

In [11]:
df_mb.columns

Index(['created', 'count', 'offset', 'artists'], dtype='str')

In [12]:
df_mb.drop(columns=['created', 'count', 'offset'], inplace=True)

In [13]:
df_mb.head()

                                                             artists
CMAT               [{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens     [{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter  [{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores       [{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença      [{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...

In [21]:
df_mb_exploded = df_mb.explode('artists').reset_index(drop=True)
# explode = pega os dicionários aninhados numa lista e transforma em linhas
df_mb_normalizado = pd.json_normalize(df_mb_exploded['artists']).reset_index(drop=True)
#o json_normalize pega esses dícionários e transforma suas prorpiedades em colunas
df_mb_normalizado.head(10)

,id,type,type-id,score,gender-id,name,sort-name,gender,country,isnis,...,ipis,disambiguation,end-area.id,end-area.type,end-area.type-id,end-area.name,end-area.sort-name,end-area.life-span.ended,life-span.end,area.life-span.begin
0,2ac533ad-f3ec-4083-a2d4-6f30393414b3,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,CMAT,CMAT,female,IE,[0000000507072282],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01d3c51b-9b98-418a-8d8e-37f6fab59d8c,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Sufjan Stevens,"Stevens, Sufjan",male,US,[0000000110253464],...,[00441776251],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1882fe91-cdd9-49c9-9956-8e06a3810bd4,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Sabrina Carpenter,"Carpenter, Sabrina",female,US,[0000000440350523],...,[00662307358],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,a8d00992-f534-47c9-ba76-bd668e8ec508,Group,e431f5f6-b5d2-343d-8b36-72607fffb74b,100,NaN,Amores,Amores,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Alceu Valença,"Valença, Alceu",male,BR,NaN,...,[00070058302],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,396a9525-0994-4542-b480-c4587feeb476,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Tinashe,Tinashe,female,US,[000000010834165X],...,"[00593900722, 00593900820]",American R&B singer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0b2665a9-14c0-499a-b9fd-46ed09bbf161,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,36d3d30a-839d-3eda-8cb3-29be4384e4a9,Zé Ibarra,"Ibarra, Zé",male,NaN,[0000000493736411],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6925db17-f35e-42f3-a4eb-84ee6bf5d4b0,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Olivia Rodrigo,"Rodrigo, Olivia",female,US,[000000047619573X],...,[00387176421],US singer‐songwriter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,d9550ac2-7bcf-4655-a3fe-24922e254a74,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,b239bbd8-aa84-4f11-8bdb-c4159e730ee5,Pabllo Vittar,"Vittar, Pabllo",non-binary,BR,[0000000466937285],...,[00862259027],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b7539c32-53e7-4908-bda3-81449c367da6,Person,b6e035f4-3ce9-331c-97df-83397230b0df,100,93452b5a-a947-30c8-934f-6a4056b151c2,Lana Del Rey,"Del Rey, Lana",female,US,"[0000000360454402, 0000000368678910]",...,"[00579892274, 00667129814]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df_mb_normalizado.columns

Index(['id', 'type', 'type-id', 'score', 'gender-id', 'name', 'sort-name',
       'gender', 'country', 'isnis', 'aliases', 'tags', 'area.id', 'area.type',
       'area.type-id', 'area.name', 'area.sort-name', 'area.life-span.ended',
       'begin-area.id', 'begin-area.type', 'begin-area.type-id',
       'begin-area.name', 'begin-area.sort-name', 'begin-area.life-span.ended',
       'life-span.begin', 'life-span.ended', 'ipis', 'disambiguation',
       'end-area.id', 'end-area.type', 'end-area.type-id', 'end-area.name',
       'end-area.sort-name', 'end-area.life-span.ended', 'life-span.end',
       'area.life-span.begin'],
      dtype='str')

In [23]:
df_mb_normalizado['tags']

0      [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
1      [{'count': 0, 'name': 'alternative rock'}, {'c...
2      [{'count': 9, 'name': 'pop'}, {'count': 1, 'na...
3                                                    NaN
4      [{'count': 2, 'name': 'pop'}, {'count': 1, 'na...
                             ...
98     [{'count': 1, 'name': 'soul'}, {'count': 1, 'n...
99     [{'count': 1, 'name': 'rap'}, {'count': 2, 'na...
100    [{'count': 2, 'name': 'rock'}, {'count': 5, 'n...
101    [{'count': 1, 'name': 'pop'}, {'count': 1, 'na...
102    [{'count': 21, 'name': 'rock'}, {'count': 21, ...
Name: tags, Length: 103, dtype: object