In [2]:
import json
import pandas as pd

In [ ]:
dados_artistas = {}

with open("../../data/raw/musicbrainz_data.json", "r", encoding="utf-8") as arquivo:
    dados_artistas = json.load(arquivo)

df_mb = pd.DataFrame.from_dict(dados_artistas, orient="index") 
#ajustando para tratar as chaves externas como as linhas da tabela, não as colunas (padrão)
# index se refere as chaves externas como linhas

df_mb.head(10)

# count mostra quantos outros artistas semelhantes batem com a nossa busca

,created,count,offset,artists
CMAT,2026-09-21T20:54:11.975Z,14,0,[{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens,2026-09-21T20:54:13.790Z,1044,0,[{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter,2026-09-21T20:54:18.346Z,658,0,[{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores,2026-09-21T20:54:20.514Z,1772,0,[{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença,2026-09-21T20:54:22.708Z,15,0,[{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...
Tinashe,2026-09-21T20:54:24.812Z,14,0,[{'id': '396a9525-0994-4542-b480-c4587feeb476'...
Zé Ibarra,2026-09-21T20:54:26.898Z,530,0,[{'id': '0b2665a9-14c0-499a-b9fd-46ed09bbf161'...
Olivia Rodrigo,2026-09-21T20:54:28.990Z,1303,0,[{'id': '6925db17-f35e-42f3-a4eb-84ee6bf5d4b0'...
Pabllo Vittar,2026-09-21T20:53:57.262Z,3,0,[{'id': 'd9550ac2-7bcf-4655-a3fe-24922e254a74'...
Lana Del Rey,2026-09-21T20:54:33.200Z,29385,0,[{'id': 'b7539c32-53e7-4908-bda3-81449c367da6'...

In [4]:
df_mb.shape

(103, 4)

In [5]:
df_mb.columns

Index(['created', 'count', 'offset', 'artists'], dtype='str')

In [6]:
df_mb = df_mb.drop(columns=['created', 'count', 'offset'])

In [7]:
df_mb.head()

                                                             artists
CMAT               [{'id': '2ac533ad-f3ec-4083-a2d4-6f30393414b3'...
Sufjan Stevens     [{'id': '01d3c51b-9b98-418a-8d8e-37f6fab59d8c'...
Sabrina Carpenter  [{'id': '1882fe91-cdd9-49c9-9956-8e06a3810bd4'...
Banda Amores       [{'id': 'a8d00992-f534-47c9-ba76-bd668e8ec508'...
Alceu Valença      [{'id': '7a08d4fb-e5c1-4c39-a99b-1908ca2e83b4'...